version: "3.9"
services:
  fastapi:
    container_name: API
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile.koyeb
    command: bash -c "alembic upgrade head && gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --reload --forwarded-allow-ips=*"
    volumes:
      - static-volume:/API/static/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

volumes:
  static-volume:
