version: "3.9"
services:
  fastapi:
    container_name: API
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - static-volume:/API/backend/static/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: DATABASE
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  static-volume:
  postgres-data:
