version: "3.9"
services:
  fastapi:
    container_name: API
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - static-volume:/API/static/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

volumes:
  static-volume:
