version: "3.9"
services:
  api:
    container_name: pipoca_api
    env_file:
      - .env
    build: .
    command: bash -c "alembic upgrade head && gunicorn -w 8 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:8000"
    volumes:
      - static-volume:/API/static/
      - /var/run/docker.sock:/var/run/docker.sock
      - temp:/API/temp/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  worker1:
    container_name: pipoca_worker_1
    env_file:
      - .env
    build: .
    command: celery -A workers worker --loglevel=info -n juiz-1@%h -Q correcao-problema,importacao-problema
    depends_on:
      - api
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp:/API/temp/

  worker2:
    container_name: pipoca_worker_2
    env_file:
      - .env
    build: .
    command: celery -A workers worker --loglevel=info -n juiz-2@%h -Q correcao-problema,importacao-problema
    depends_on:
      - api
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp:/API/temp/

  worker3:
    container_name: pipoca_worker_3
    env_file:
      - .env
    build: .
    command: celery -A workers worker --loglevel=info -n juiz-3@%h -Q correcao-problema,importacao-problema
    depends_on:
      - api
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp:/API/temp/

  worker4:
    container_name: pipoca_worker_4
    env_file:
      - .env
    build: .
    command: celery -A workers worker --loglevel=info -n juiz-4@%h -Q correcao-problema,importacao-problema
    depends_on:
      - api
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp:/API/temp/

  worker5:
    container_name: pipoca_worker_5
    env_file:
      - .env
    build: .
    command: celery -A workers worker --loglevel=info -n juiz-5@%h -Q correcao-problema,importacao-problema
    depends_on:
      - api
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp:/API/temp/

  flower:
    container_name: pipoca_flower
    env_file:
      - .env
    build: .
    image: mher/flower
    command: /bin/sh -c "mkdir -p /flower_data && celery && celery -A workers flower --basic-auth=${FLOWER_BASIC_AUTH} --state_save_interval=10000 --persistent=True --db='flower_data/flower_db' --tasks-columns='name,uuid,state,args,result,received,started,runtime,worker,retries,expires'"
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    volumes:
      - flower-data:/API/flower_data

  rabbitmq:
    container_name: pipoca_rabbitmq
    env_file:
      - .env
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  postgres:
    container_name: pipoca_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  static-volume:
  postgres-data:
  flower-data:
  temp:
